env:
    - ZMQ="git://github.com/zeromq/zeromq4-x.git -b v4.0.4" SODIUM="git://github.com/jedisct1/libsodium.git -b 0.5.0"
before_install:
    - sudo apt-get install uuid-dev
    - if [ -n "$SODIUM" ]; then 
    -  git clone --depth 1 $SODIUM libsodium
    -  cd libsodium
    -  ./autogen.sh
    -  ./configure
    -  make
    -  sudo make install
    -  cd ../
    - fi
    - git clone --depth 1 $ZMQ zmqlib
    - cd zmqlib
    - ./autogen.sh
    - ./configure
    - make
    - sudo make install
    - sudo /sbin/ldconfig
    - cd ..
language: node_js
node_js:
    - 0.10
script: "npm run-script test-cov"
before_script:
    - npm install socket.io-zeromq-server
    - npm install pm2
    - ./node_modules/.bin/pm2 start ./node_modules/.bin/socket.io-zeromq-server -i 1
after_script:
    - npm install coveralls
    - cat ./coverage/lcov.info | coveralls"
